### ISSUE TITLE
Player ID Feature

### ISSUE THREAD

**Issue by BarronZeta** [sguo1123/SMMO-Player-Checker#1]
First off, I really appreciate this project and its usefulness. While I don't ever get many returns, the few are always nice. Is there any plan to implement a player ID add or search feature? While adding guilds is easy enough, the nice inactive whales are typically un-guilded and thus harder to find. Thanks!

**Comment by HugTeddy** [comment]
Resolved in b0d9ab9a7b148ef4b342d55cd49dc28ba089909f
